### PR TITLE
Update Chinese translations 

### PR DESCRIPTION
**Pull request by Mayomi**

### CODE REVIEW

**Comment by ADeeeee** [comment]
I could approve this is the official translation in game.

@Mayomi Are you already translating all the zh-CN or zh-TW? I've found that last time it was translated about two years ago and it's just a regional translation before Splatoon 3 came out. I could help for the translation of zh-TW, which is my mother tongue, if you have not worked on it yet.

**Comment by Mayomi** [comment]
> I could approve this is the official translation in game.
> 
> @Mayomi Are you already translating all the zh-CN or zh-TW? I've found that last time it was translated about two years ago and it's just a regional translation before Splatoon 3 came out. I could help for the translation of zh-TW, which is my mother tongue, if you have not worked on it yet.

I translated these files only. I am very honored if you want to help me for zh-TW translation.

**Comment by fetus-hina** [comment]
Thank you guys.
I've merged this pull request. It will be available in a short while.

谢谢 謝謝

**Comment by ADeeeee** [comment]
I've pulled this MR and already working on it and it should be done before the end of this weekend. 

A PR will be created once it's done. You guys are really cool. See you soon.

**Pull request merged**
