### PR TITLE
Shifty stations for Final Splatfest

### PR DESCRIPTION
**Pull request by fetus-hina**
- [ ] Add Shifty-Station layouts
  - [x] Add exists 23 layouts
    - [x] Add data (ja)
    - [x] Translations (en)
    - [ ] Translations (other; necessary to prepare for them because we use a special format "Shifty: NAME")
  - [x] Add new layout ("DEAR SENPAI")
    - [x] Add data (ja)
    - [x] Translation (en)
    - [ ] Translations (other; necessary to prepare for them because we use a special format "Shifty: NAME")
  - [x] Modify exist battles
  - [x] Add helper for POST API (users may post past Splatfest. With [a few exceptions](https://github.com/fetus-hina/stat.ink/blob/7f503e7eef60405565d872e1af1deda4f334baee/migrations/m190621_194311_update_old_splatfest_shifty.php#L158-L160), we can identify which stage is.)
  - [x] Modify search behavior
- [ ] Add "Senpai Cannon" and "Iida Bomb"
  - [x] Add data (ja)
  - [ ] Translations

### CODE REVIEW

**Comment by fetus-hina** [comment]
@frozenpandaman Could you tell me when NOA announces Shifty Station layout names, "Senpai Cannon" or "Marina/Iida Bomb"?

**Comment by fetus-hina** [comment]
https://splatoonus.tumblr.com/post/185753477632/were-receiving-reports-that-the-final-shifty

**Comment by frozenpandaman** [comment]
@fetus-hina Haha, was just about to comment that link. :D Yay!

**Comment by fetus-hina** [comment]
I'm thinking about when to merge this branch.
The main issues that remain are localization issues and they not have any major impact to the system.

The English names of _"Senpai-Canon"_ and _"Iida-bomb_" affect the database because of the mechanism we have adopted.
However, those data are valid only at the "death reasons" (causes of death), and I don't know the user agent that may transmit them (we haven't IkaLog for Splatoon 2!).

The name of Shifty Stations will take a very long time to come up.

So, it might be better to merge this branch quickly and get rid of the clutter of the work.

**Pull request merged**
